<NavigationScreenManager>:
    Screen:
        name: "main_menu_screen"
        BoxLayout:
            orientation: "vertical"
            Button:
                text: "View All Publishers"
                on_release: app.manager.show_all_names_screen()
            Button:
                text: "Lookup by Tag"
            TextInput:
                text: "to implement later"
                size_hint_y: .3
